#!/bin/bash
#
# missdeps: check for missing deps of installed packages
#
# missdeps uses revdep listinst to check for missing dependencies, then
# outputs their immediate dependents
#
# Petar Petrov, slackalaxy at gmail dot com

missing=$(prt-get listinst | xargs prt-get depends | grep "\[ \]" | sed "s:\[ \] ::g")
misspkg=$(prt-get listinst | xargs prt-get depends | grep "\-- missing packages")

if [ -z "$missing" ] && [ -z "$misspkg" ]; then
    echo "** no missing deps"
    exit 0
else
    echo "** checking for missing deps"
    echo "-- ([ ] missing, [i] = installed dependents)"
fi

# Report missing rependencies...
for m in ${missing[@]}; do
  echo -e "[ ] $m"
  dependents=$(prt-get dependent $m)
  
  # ... and find their immediate dependents
  for d in ${dependents[@]}; do
    deps+=$(echo "$d ")
  done
  
done

# Remove repetitive dependents
norep=$(echo -e "${deps[@]}" | sed "s: :\n:g" | sort -u)

# Print the dependents
for n in ${norep[@]}; do
  echo -e "[i] $n"
done 

# are there missing deps that have no ports?
if [ ! -z "$misspkg" ]; then
  prt-get listinst | xargs prt-get depends | grep -v "\["
fi
