#!/bin/bash
#
# prtdepadd: add missing dependencies to port
#
# Petar Petrov, slackalaxy at gmail dot com

# is input empty?
if [ "$1" = "" ]; then
	echo "Usage: prtdepadd <port>"
	exit 1
fi

port="$1"

# does port exist?
if [ ! -d $port ]; then
	echo "$port does note exist."
	exit 1
fi

# does pkgfile exist?
if [ ! -f $port/Pkgfile ]; then
	echo "$port does not contain a Pkgfile."
	exit 1
fi

# do we have write permissions?
if [ ! -w "$port/Pkgfile" ]; then
	echo "$port/Pkgfile is not writable."
	exit 1
fi

# is the port installed?
if prt-get isinst $port | grep "not" > /dev/null; then
	echo "$port is not installed."
	exit 1
fi

# get what is already listed
depa=$(grep "# Depends on:" $port/Pkgfile)

# find deps independently
depb=$(finddeps $port | grep -v "core" | awk '{print $1}')

# combine them both
depc=$(echo "$depa $depb" | cut -c14- | sed "s: :\n:g" | sort -u | tr '\n' ' ')

# write to Pkgfile
sed -i "s/$depa/$(echo "# Depends on:" $depc)/" $port/Pkgfile
echo "=======> Processed $port"
