#!/bin/bash
#
# prtdepsfix: add any new deps to the existing deps of a port
#
# Calculate dependencies by calling finddeps, then add update the deps
# information of the port (non-reduncant).
#
# Petar Petrov, slackalaxy at gmail dot com

# is input empty?
if [ "$1" = "" ]; then
    echo "Usage: prtdepsfix <port>"
    exit 1
fi

# no options used with prtdepsfix
if [[ $1 == -* ]]; then
    echo -e "Invalid input "$1". Usage: prtdepsfix <port>"
    exit 1
fi

port="$1"
portpath=$(prt-get info "$port" | grep Path | sed "s|Path:||" | sed "s| ||g")
echo "$portpath/$port"

newdeps=$(echo -n `finddeps $port | grep -v "core" | awk '{print $1}'`)
echo "** calculating new deps"

sed -i "s|# Depends on:|# Depends on: $newdeps|" $portpath/$port/Pkgfile
findredundantdeps -f $port
