#!/bin/bash
#
# revlibpkg: find ports that contain missing libs
#
# revlibpkg uses revdep to check for missing .so files, then searches
# with prt-get to find which ports contain them. Redundant libraries are
# removed, reporting a simple list.
#
# Petar Petrov, slackalaxy at gmail dot com
#
# Thanks to farkuhar from #crux @libera.chat for various modifications,
# especially with awk.

# Is input empty?
if [ "$1" = "" ]; then
    echo "Input is empty. Usage: $0 [package...]"
    exit 1
fi

# No options used with revlibpkg
for t in "$@"; do
  if [ "${t:0:1}" = "-" ]; then
    echo -e "Invalid input $t. Usage: $0 [package...]"
    exit 1
  fi
done

# Count input. https://askubuntu.com/a/939626
echo -e "** checking $# package(s)"

for i in "$@"; do
  LIB=""
  
  # Check if input is installed first.
  if prt-get isinst "$i" >/dev/null; then
    
    # Search by awk for a pattern. Then translate new lines to space.
    ILIB=$(revdep "$i" -vvv | awk -F ":" '/(missing library)/ {print $3}' | uniq | tr '\n' ' ')
    
    # Collect the missing libs, if any.
    if [ -z "$ILIB" ]; then
      echo "$i: ok"
    elif [ -n "$ILIB" ]; then
      LIB+="$ILIB "
      for l in ${LIB[@]} ; do
        # https://www.gnu.org/software/gawk/manual/html_node/String-Functions.html
        revport=$(prt-get fsearch ${l} | awk '/(Found in)/ {print gensub(/.*\/(.+):/,"\\1","g",$NF)}' | tr '\n' ' ')
        echo -e "$i: missing <$l> found in: $revport"
      done
    fi

  else
    echo "$i: not installed"
  fi

done
